name: Deploy Prod

concurrency: production

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_SITE_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SITE_KEY_SECRET }}
          aws-region: ap-northeast-1
      - name: Deploy
        run: |
          cd site
          aws s3 sync . s3://golftrainer.evertras.com
